// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://relmsivfupkuidrqhndi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlbG1zaXZmdXBrdWlkcnFobmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTkzNjYsImV4cCI6MjA2NTQ3NTM2Nn0.mS9kfv1OSB-Mc7jsVV9qnjslhmtkGhNvz_PttRXVDFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);